language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
matrix:
  fast_finish: true
sudo: false
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
install:
  - composer install
  - composer update --with-dependencies mediawiki/mediawiki-codesniffer phpunit/phpunit
script:
  - composer test
